コピペ

diff --git a/.github/workflows/my_github_workflow.yaml b/.github/workflows/my_github_workflow.yaml
--- a/.github/workflows/my_github_workflow.yaml
+++ b/.github/workflows/my_github_workflow.yaml
@@ -1,46 +1,78 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-
-# pulled from repo
-name: "Rubocop"
-
-on:
-  push:
-    branches: [ $default-branch, $protected-branches, feature/test ]
-  pull_request:
-    # The branches below must be a subset of the branches above
-    branches: [ $default-branch ]
-
+name: reviewdog
+on: [pull_request]
+permissions:
+  contents: read
+  pull-requests: write
 jobs:
   rubocop:
+    name: runner /rubocop
     runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Check out code
+        uses: actions/checkout@v3
+      - uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: 3.1.2
+      - name: rubocop
+        uses: reviewdog/action-rubocop@v2
+        with:
+          rubocop_version: gemfile
+          rubocop_extensions: rubocop-rails:gemfile
+          github_token: ${{ secrets.github_token }}
+          reporter: github-pr-review
 
-    # If running on a self-hosted runner, check it meets the requirements
-    - name: Set up Ruby
-      uses: ruby/setup-ruby@v1
 
-    - name: Install dependencies
-      run: ls -la && bundle install && ls -la
 
-    - name: Rubocop run
-      run: |
-        bash -c "
-          bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
-          [[ $? -ne 2 ]]
-        "
 
-    - name: Current Directory State
-      run: ls -la
 
-    - name: Upload Sarif output
-      uses: github/codeql-action/upload-sarif@v2
-      with:
-        sarif_file: rubocop.sarif
+
+
+
+
+
+# # This workflow uses actions that are not certified by GitHub.
+# # They are provided by a third-party and are governed by
+# # separate terms of service, privacy policy, and support
+# # documentation.
+
+# # pulled from repo
+# name: "Rubocop"
+
+# on:
+#   push:
+#     branches: [ $default-branch, $protected-branches, feature/test ]
+#   pull_request:
+#     # The branches below must be a subset of the branches above
+#     branches: [ $default-branch ]
+
+# jobs:
+#   rubocop:
+#     runs-on: ubuntu-latest
+#     strategy:
+#       fail-fast: false
+
+#     steps:
+#     - name: Checkout repository
+#       uses: actions/checkout@v3
+
+#     # If running on a self-hosted runner, check it meets the requirements
+#     - name: Set up Ruby
+#       uses: ruby/setup-ruby@v1
+
+#     - name: Install dependencies
+#       run: ls -la && bundle install && ls -la
+
+#     - name: Rubocop run
+#       run: |
+#         bash -c "
+#           bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
+#           [[ $? -ne 2 ]]
+#         "
+
+#     - name: Current Directory State
+#       run: ls -la
+
+#     - name: Upload Sarif output
+#       uses: github/codeql-action/upload-sarif@v2
+#       with:
+#         sarif_file: rubocop.sarif
